app:
  name: "Fundos de Investimentos"
  indices:
    cdi:
      description: "CDI"
      url: "https://api.bcb.gov.br/dados/serie/bcdata.sgs.12/dados?formato=json"
      path: "./dataset/cdi/bcdata.sgs.12.json"
    ibovespa:
      description: "Ibovespa"
      path: "./dataset/ibov/ibovespa.json"
      start_date: "01/01/2024"
      end_date: "27/07/2024"
  cvm:
    fundo:
      cad:
        description: "Informação Cadastral"
        url: "https://dados.cvm.gov.br/dados/FI/CAD/DADOS/cad_fi.csv"
        path: "./dataset/cad/cad_fi.csv"
      informe:
        description: "Informes Diários"
        url: "https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_{year}{month}.zip"
        path: "./dataset/infdiario"
        start_date: "2024/01/01"
        end_date: "2024/08/01"
        historical: false
      carteira:
        description: "Carteira"
        url: "https://dados.cvm.gov.br/dados/FI/DOC/CDA/DADOS/cda_fi_{year}{month}.zip"
        path: "./dataset/carteira"
        start_date: "2024/02/02"
        end_date: "2024/08/01"
        historical: false
