---
indices:
  ibovespa:
    end_date: 13/08/2023
    start_date: 24/08/2022
    description: Ibovespa
    path: ./dataset/ibov/ibovespa.json
  cdi:
    url: https://api.bcb.gov.br/dados/serie/bcdata.sgs.12/dados?formato=json&dataInicial={start_date}&dataFinal={end_date}
    path: ./dataset/cdi/bcdata_cdi.json
    end_date: 13/08/2023
    start_date: 24/07/2022
    description: CDI
cvm:
  fundo:
    cadastro:
      path: ./dataset/cad/cad_fi.csv
      url: https://dados.cvm.gov.br/dados/FI/CAD/DADOS/cad_fi.csv
      description: Informação Cadastral
    carteira:
      start_date: 24/08/2023
      end_date: 13/08/2024
      path: ./dataset/carteira
      historical: false
      url: https://dados.cvm.gov.br/dados/FI/DOC/CDA/DADOS/cda_fi_{year}{month}.zip
      description: Composição e Diversificação das Aplicações
    informe:
      path: ./dataset/infdiario
      start_date: 24/08/2021
      description: Informes Diários
      end_date: 13/08/2024
      url: https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_{year}{month}.zip
      historical: false
