---
title: Configuração de Indicadores e CVM
type: object
properties:
  indices:
    type: object
    title: Índices
    properties:
      ibovespa:
        type: object
        title: Ibovespa
        properties:
          end_date:
            type: date
            format: date
            title: Data de Fim
          start_date:
            type: date
            format: date
            title: Data de Início
          path:
            type: string
            title: Caminho do Arquivo
      cdi:
        type: object
        title: CDI
        properties:
          url:
            type: string
            format: uri
            title: URL
          path:
            type: string
            title: Caminho do Arquivo
  cvm:
    type: object
    title: CVM
    properties:
      fundo:
        type: object
        title: Fundo
        properties:
          cadastro:
            type: object
            title: Informação Cadastral
            properties:
              path:
                type: object
                title: Caminho do Arquivo
              url:
                type: string
                format: uri
                title: URL
          carteira:
            type: object
            title: Composição e Diversificação das Aplicações
            properties:
              start_date:
                type: date
                format: date
                title: Data de Início
              end_date:
                type: date
                format: date
                title: Data de Fim
              path:
                type: string
                title: Caminho do Arquivo
              historical:
                type: boolean
                title: Histórico
              url:
                type: string
                format: uri
                title: URL
          informe:
            type: object
            title: Informes Diários
            properties:
              path:
                type: string
                title: Caminho do Arquivo
              start_date:
                type: date
                format: date
                title: Data de Início
              end_date:
                type: date
                format: date
                title: Data de Fim
              url:
                type: string
                format: uri
                title: URL
              historical:
                type: boolean
                title: Histórico
